### ISSUE TITLE
Getting an unhandled error event

### ISSUE THREAD

**Issue by marie-dk** [AlexDisler/cordova-splash#10]
I thought someone may have created a tool to automate generation of splash graphics... and Google directed me here :-)  Very nice.... but I am getting this error:

    $ cordova-splash

    Checking Project & Splash

     ✓  platforms found: ios, android
     ✓  splash.png exists
     ✓  config.xml exists

    Generating splash screen for ios
    
    events.js:85
         throw er; // Unhandled 'error' event
               ^
    Error: spawn identify ENOENT
       at exports._errnoException (util.js:746:11)
       at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
       at child_process.js:1137:20
       at process._tickCallback (node.js:355:11)

Installed cordova-splash today, and using Cordova version 4.2.0

**Comment by marie-dk** [comment]
Doh! ... Needed to install imagemagick. Problem solved ;-)

**Comment by alirezamirian** [comment]
The same problem solved for me by reinstalling imagemagick with **Install legacy utilities (e.g. convert)** option checked.
![image](https://cloud.githubusercontent.com/assets/3150694/20858283/c87517a2-b957-11e6-8a14-851d20489e52.png)
