### ISSUE TITLE
Splash Screen Not Showing on Android Device

### ISSUE THREAD

**Issue by sam3k** [AlexDisler/cordova-splash#11]
I have successfully gotten the splash (and icon screen) to load on iOS but on my Samsung Galaxy 3; I cannot see the splash screen. Instead, I get a black screen instead. It is worth noting that:
- the icon generated by cordova-icon does show up on my Galaxy. 
- the images are generated successfully platforms/android/ant-build/res (I assume Samsung Galaxy portrait size would use drawable-port-xhdpi/screen.png since its screen resolution is 720x1280)

Here is the output which seems fine:

``` bash
$ cordova run android
Running command: /Users/Sam/Projects/app/c3c/hooks/after_prepare/cordova-icon.sh /Users/Sam/Projects/app/c3c

 Checking Project & Icon

  ✓  platforms found: ios, android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for ios

  ✓  icon-60@2x.png created
  ✓  icon-60.png created
  ✓  icon-50@2x.png created
  ✓  icon-50.png created
  ✓  icon-40@2x.png created
  ✓  icon-40.png created
  ✓  icon-72.png created
  ✓  icon-76@2x.png created
  ✓  icon-60@3x.png created
  ✓  icon-72@2x.png created
  ✓  icon-76.png created
  ✓  icon-small@2x.png created
  ✓  icon-small.png created
  ✓  icon.png created
  ✓  icon@2x.png created

 Generating Icons for android

  ✓  drawable/icon.png created
  ✓  drawable-ldpi/icon.png created
  ✓  drawable-mdpi/icon.png created
  ✓  drawable-hdpi/icon.png created
  ✓  drawable-xhdpi/icon.png created


 Checking Project & Splash

  ✓  platforms found: ios, android
  ✓  splash.png exists
  ✓  config.xml exists

 Generating splash screen for ios

resize arg
arg 1536x2048
resize arg
arg 320x480
resize arg
arg 640x960
resize arg
arg 750x1334
resize arg
arg 2048x1536
resize arg
arg 640x1136
resize arg
arg 2208x1242
resize arg
arg 1242x2208
resize arg
arg 768x1024
resize arg
arg 1024x768
  ✓  Default~iphone.png created
  ✓  Default@2x~iphone.png created
  ✓  Default-568h@2x~iphone.png created
  ✓  Default-Landscape~ipad.png created
  ✓  Default-Portrait~ipad.png created
  ✓  Default-667h.png created
  ✓  Default-Portrait@2x~ipad.png created
  ✓  Default-Landscape@2x~ipad.png created
  ✓  Default-Landscape-736h.png created
  ✓  Default-736h.png created

 Generating splash screen for android

resize arg
arg 320x200
resize arg
arg 800x480
resize arg
arg 720x1280
resize arg
arg 1280x720
resize arg
arg 480x800
resize arg
arg 480x320
resize arg
arg 200x320
resize arg
arg 320x480
  ✓  drawable-land-ldpi/screen.png created
  ✓  drawable-port-ldpi/screen.png created
  ✓  drawable-port-mdpi/screen.png created
  ✓  drawable-land-mdpi/screen.png created
  ✓  drawable-land-hdpi/screen.png created
  ✓  drawable-port-hdpi/screen.png created
  ✓  drawable-port-xhdpi/screen.png created
  ✓  drawable-land-xhdpi/screen.png created
```

**Comment by sam3k** [comment]
So I got it to work by manually adding the path to all android splash screens to the config.xml

```xml
<widget>
  <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="10000" />
    
    <platform name="android">
        <splash src="platforms/android/ant-build/res/drawable-land-hdpi/screen" density="port-hdpi"/>
        <splash src="platforms/android/ant-build/res/drawable-land-ldpi/screen" density="port-ldpi"/>
        <splash src="platforms/android/ant-build/res/drawable-land-mdpi/screen" density="port-mdpi"/>
        <splash src="platforms/android/ant-build/res/drawable-land-xhdpi/screen" density="port-xhdpi"/>
        <splash src="platforms/android/ant-build/res/drawable-port-hdpi/screen" density="port-hdpi"/>
        <splash src="platforms/android/ant-build/res/drawable-port-ldpi/screen" density="port-ldpi"/>
        <splash src="platforms/android/ant-build/res/drawable-port-mdpi/screen" density="port-mdpi"/>
        <splash src="platforms/android/ant-build/res/drawable-port-xhdpi/screen" density="port-xhdpi"/>
    </platform>
</widget>
```

If I am suppose to add it manually to the config.xml then that is not clear in the README afaik.

**Comment by daviddahl** [comment]
@sam3k That config.xml tweak does not work for me at all. Again, all of this works well on iOS, bit not on Android

**Comment by sam3k** [comment]
@daviddahl did you make sure that the splash graphics are getting generated in the platforms/android/ant-build/res/**/screen directories? Could you post a gist of your entire config here?

**Comment by daviddahl** [comment]
They were not. They were being generated into platforms/android/res/ - and I changed the config.xml for this, but the android support libs failure happened when I rm'd and added the platform again. I will dig out of this problem first.

**Comment by BrunoMarchesson** [comment]
Hello,

Same issue here. From my current investigations, cordova-splash properly generates the resource files, but the "cordova build" command first delete them and then complains that it does not find it anymore (using the -v verbose option)...

**Comment by BrunoMarchesson** [comment]
For information, using the after_prepare hook as mentioned on cordova-icon project solved my issue (splashscreen files are deleted during the prepare phase and thus created again by the hook).

Hope this helps

**Comment by daviddahl** [comment]
So this is still not working for me... My current error is: Refused to load the image 'android-webview-video-poster:default_video_poster/2962627746536845316' because it violates the following Content Security Policy directive: "default-src 'self' https: wss: data: gap: https://ssl.gstatic.com". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by mariowise** [comment]
Can anybody help me to solve this ??

**Comment by yassin-bennaceur** [comment]
@BrunoMarchesson I am facing the same problem that you had. the files are correctly generated but the cordova build deletes them then complains. any workaround for this ?

**Comment by aaronprojects** [comment]
Still no solution for this? My splash screen files are generated correctly and linked in the config.xml, but the splash screen is still not showing since I updated to cordova 5.1.1.

**Comment by mdumouchel** [comment]
I also am seeing this issue anyone have a solution to this.  I tried both the xml change and the hook.  Seems like pretty old issue to still be open.

**Comment by BrunoCartier** [comment]
Closing since talking about possibly outdated problems.
Fell free to open a new issue if needed.
