### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by aaslun** [AlexDisler/cordova-splash#12]
Hi there and thanks for a great script! I used the cordova-icon script and it worked great, although I got problems with the cordova-splash execution. I installed it through npm and all seemed OK, until I tried to run it. I get this "Unhandled 'error' event" problem.
Any ideas?

Here is the feedback I get in the console when running cordova-splash:

	Checking Project & Splash

	  ✓  platforms found: ios
	  ✓  splash.png exists
	  ✓  config.xml exists

	 Generating splash screen for ios

	events.js:85
	      throw er; // Unhandled 'error' event
	            ^
	Error: spawn identify ENOENT
	    at exports._errnoException (util.js:746:11)
	    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
	    at child_process.js:1144:20
	    at process._tickCallback (node.js:355:11)

**Comment by yaworsw** [comment]
I was able to resolve this problem by making sure that `identify` was added to my `PATH`.  I did it by adding

```
export PATH=$PATH:/usr/local/Cellar/imagemagick/6.9.1-4/bin
```

to my `~/.bashrc` file though creating symlinks would also be a valid solution.

http://stackoverflow.com/questions/8723506/sh-identify-command-not-found-imagemagick-rails-3

**Comment by aaslun** [comment]
Thanks a lot for looking into this! I've switched shell from bash to fish, which was the cause of this. Your reply got me further into the execution, it now seems there's something corrupt with my Imagemagick install as well. There seems to be some missing or dislocated libraries, I'm cleaning and reinstalling Imagemagick at the moment. Hopefully this will do the trick.

**Comment by BrunoCartier** [comment]
Hey @aaslun, is your problem solved? If so please close the issue.

**Comment by zyf0330** [comment]
Actually, you must check legacy tools like convert when install it.
