### ISSUE TITLE
Size of Images

### ISSUE THREAD

**Issue by davidfig** [AlexDisler/cordova-splash#13]
Thanks for the useful utility. 

Quick comment on the sizing of the original image: similar to ionic framework, you should try to use images that are 2208x2208 px with a center square of about 1200x1200 px. You can also use larger images with similar proportions.

This seemed to work in my tests (and it took me a while to figure out).

**Comment by sibelius** [comment]
@davidfig could u send a PR to add this to the docs?

**Comment by davidfig** [comment]
Sent. (Should have thought of that.)
