### ISSUE TITLE
Command failed: convert: unable to open image

### ISSUE THREAD

**Issue by webeks** [AlexDisler/cordova-splash#20]
When trying to run I get error ... 

`bash-3.2$ cordova-splash

 Checking Project & Splash

  ✓  platforms found: ios
  ✓  splash.png exists
  ✓  config.xml exists

 Generating splash screen for ios

resize arg
arg 1242x2208
resize arg
arg 750x1334
resize arg
arg 640x1136
resize arg
arg 2208x1242
resize arg
arg 2048x1536
resize arg
arg 1536x2048
resize arg
arg 1024x768
resize arg
arg 768x1024
resize arg
arg 640x960
resize arg
arg 320x480
{ [Error: Command failed: convert: unable to open image `platforms/ios/Plantar Fasciitis Treatment/Resources/splash/Default-Landscape~ipad.png': No such file or directory @ error/blob.c/OpenBlob/2702.
convert: WriteBlob Failed `platforms/ios/Plantar Fasciitis Treatment/Resources/splash/Default-Landscape~ipad.png' @ error/png.c/MagickPNGErrorHandler/1630.
] timedOut: false, killed: false, code: 1, signal: null }`

**Comment by webeks** [comment]
found the problem:

You need to switch to proper folder structure for 4.0.1 ios cordova lib

//splashPath : 'platforms/ios/' + projectName + '/Resources/splash/',
splashPath : 'platforms/ios/' + projectName + '/Images.xcassets/LaunchImage.launchimage/',

I just switched in my local module code, hadnt have time to proper check for ios lib version to create pull req :( Hope someone else has time ...

**Comment by webeks** [comment]
One more thing ... this only happens when using CORDOVA to build ... if I use PHONEGAP it is still Resources/splash as target dir

**Comment by BrunoCartier** [comment]
Thanks for opening this issue. Location has been changed with PR #17.
