### ISSUE TITLE
iOS resources are not automatically picked up by XCode project

### ISSUE THREAD

**Issue by ChristianWeyer** [AlexDisler/cordova-splash#28]
Hi - and thank you very much for this great tool! :)

cordova-splash puts all iOS-related resources into an .xcasetts folder - fine.
But the standard Cordova project wants to work with the Resources folder and thus the generated resources are not being picked up, but still the old defaults.

I am using Cordova-iOS 3.9.1 - as there are some essential plugins (like https://github.com/Telerik-Verified-Plugins/WKWebView) that do not work with the 4.x tooling.

Thanks.

**Comment by BrunoCartier** [comment]
Hi,

Please try a older version of `cordova-splash`, compatible with old paths, for example, `0.3.0`.

**Comment by ChristianWeyer** [comment]
Alright. Thanks!
