### ISSUE TITLE
does not allow updating icons ?

### ISSUE THREAD

**Issue by joeblew99** [AlexDisler/cordova-splash#36]
once i have generated the icons and splash for my platforms, if i change the icon.png or splash.png, regenerate them, and then rebuild my platforms, i dont see the new icon and splash images.

Maybe i am doing something wrong ?

**Comment by BrunoCartier** [comment]
Is the issue present on both platforms? (iOS + Android)
Could you please give us your `config.xml` file?

**Comment by BrunoCartier** [comment]
No response, closing. Feel free to re-open if needed.
