### ISSUE TITLE
Config.xml doesn't get modified

### ISSUE THREAD

**Issue by unclespode** [AlexDisler/cordova-splash#37]
All the images are created properly, but I don't see any adjustments made to config.xml. It detects it, and even if I specify the file, it still doesn't adjust it.

**Comment by BrunoCartier** [comment]
No `config.xml` changes have to be done for splash files.
In fact, ensure there is no `splash` tag in your file. See this: https://github.com/AlexDisler/cordova-icon/issues/82
Only needed things are the classical instructions for the cordova splash plugin:
```xml
<plugin name="cordova-plugin-splashscreen" spec="~3.1.0" />
<preference name="SplashScreen" value="screen" />
<feature name="SplashScreen">
    <param name="onload" value="true" />
</feature>
```

**Comment by unclespode** [comment]
I had the same concern, but then realised that despite this - it worked.

Perhaps the documentation needs updating to say that you shouldn't expect any changes? I was left wondering if it had done anything.
