### ISSUE TITLE
command failed 

### ISSUE THREAD

**Issue by iamgoodbytes** [AlexDisler/cordova-splash#5]
Hi Alex, thanks for sharing cordova-splash, it has saved me a lot of time already. Because I was missing iPhone6 and 6-Plus images (the default cordova image kept showing up) I updated cordova-splash and the images are generated perfectly. However, I'm now getting the following errors, I thought it would be useful to mention this. 

 [Error: Command failed: convert: unable to open image `platforms/android/res/drawable-port-ldpi/screen.png': No such file or directory @ error/blob.c/OpenBlob/2643.
convert: WriteBlob Failed`platforms/android/res/drawable-port-ldpi/screen.png' @ error/png.c/MagickPNGErrorHandler/1804.
] timedOut: false, killed: false, code: 1, signal: null }

**Comment by maartenvandillen** [comment]
Although in one project it worked fine, I now get the same kind of error with another project: 

{ [Error: Command failed: convert: unable to open image `platforms/android/res/drawable-land-ldpi/screen.png': No such file or directory @ error/blob.c/OpenBlob/2709.
convert: WriteBlob Failed `platforms/android/res/drawable-land-ldpi/screen.png' @ error/png.c/MagickPNGErrorHandler/1805.
] timedOut: false, killed: false, code: 1, signal: null }

All output above that error seems ok, the last lines above the error are (when Generating splash screen for Android):
resize arg
arg 320x480

**Comment by maartenvandillen** [comment]
I think I found the cause of this. I had some old splash screen configurations in my config.xml. These were pointing to non-existent directories. After creating these directories, the errors went away. I also removed the old splash screen config lines since they are no longer needed, which probably would have fixed it also.

**Comment by SeanHub** [comment]
I'm having the same error when generating images for an iOS project. The images should be stored in a 'Images.xcassets' folder within the iOS project folder, but the command line attempts to look for a 'splash' folder within the 'Resources' folder within the same iOS project folder.

**Comment by BrunoCartier** [comment]
@maartenvandillen Thanks for sharing your solution.
@SeanHub cordova-splash now has a `--xcode-old` option allowing you to choose the output folder (old or new Cordova version - see documentation).
