### ISSUE TITLE
I see it working, but its not "working"

### ISSUE THREAD

**Issue by dogpatchmedia** [AlexDisler/cordova-splash#6]
Hi. I see it says its making the screens from the master splash png, and I see files in the folders in the app root. But when I compile the app with cordova, the splash screen doesnt work. Any advice about what I might be doing wrong?

**Comment by peterschwarz** [comment]
Have you made sure that you have 

```
<preference name="SplashScreen" value="screen"/>
``` 

in your `config.xml`?

**Comment by dogpatchmedia** [comment]
Yeah I figured that out. Thanks for getting back to me. Sorry I forgot to mark it as resolved. I'm not good at git hub yet.

**Comment by BrunoCartier** [comment]
Closing issue, since resolved.
