### ISSUE TITLE
Create a tag

### ISSUE THREAD

**Issue by reiz** [AlexDisler/cordova-splash#8]
Somebody submitted this project at VersionEye. But without a tag there is not much to track. Why not creating a first SNAPSHOT tag? And please use [semantic versioning](http://semver.org) ;-)

**Comment by AlexisCaffa** [comment]
how can i create a tag? If i have a fork...

**Comment by reiz** [comment]
You can do it like this: 

```
git tag -a v1.0.0 -m 'My very first tag!' 
git push origin master --tags
```

**Comment by BrunoCartier** [comment]
The project will now use tags, and we will do our best to respect semantic versioning :)
https://github.com/AlexDisler/cordova-splash/tags

Thanks :+1:
